name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Run Unit Tests
        run: mvn test
        
      - name: Build and Package with Maven
        run: mvn package
        
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build Container Image
        run: docker build -t my-app .
        
      - name: Tag Container Image
        run: |
          docker tag my-app ${{ secrets.DOCKER_USER }}/my-app:${{ github.sha }}
          docker tag my-app ${{ secrets.DOCKER_USER }}/my-app:latest
          
      - name: Push Container Image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/my-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/my-app:latest
