name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Unit Tests
        run: mvn test
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t my-app .
      - name: Tags
        run: |
          docker tag back ${{ secrets.DOCKER_USER }}/my-app:${{ github.sha }}
          docker tag back ${{ secrets.DOCKER_USER }}/my-app:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/my-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/my-app:latest
